config/routes.rb
Rails.application.routes.draw do
  if Rails.application.multi_tenancy?
    constraints subdomain: 'showcase' do
      root to: 'static_pages#showcase', as: :showcase
    end

    constraints subdomain: 'login' do
      get '/signup', to: 'tenants#new'
      get '/is_available', to: 'tenants#is_available'
      
      resource :tenants, only: [:create]
    end
  end

  constraints subdomain: /.*/ do
    root to: 'static_pages#root'
    
    get '/roadmap', to: 'static_pages#roadmap'
    get '/pending-tenant', to: 'static_pages#pending_tenant'
    get '/blocked-tenant', to: 'static_pages#blocked_tenant'
    
    devise_for :users, :controllers => {
      :registrations => 'registrations',
      :sessions => 'sessions'
    }
    
    resources :tenants, only: [:show, :update]
    resources :users, only: [:index, :update]
    resources :o_auths, only: [:index, :create, :update, :destroy]
    get '/o_auths/:id/start', to: 'o_auths#start', as: :o_auth_start
    get '/o_auths/:id/callback', to: 'o_auths#callback', as: :o_auth_callback
  
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      resource :follows, only: [:create, :destroy]
      resources :follows, only: [:index]
      resource :likes, only: [:create, :destroy]
      resources :likes, only: [:index]
      resources :comments, only: [:index, :create, :update, :destroy]
      resources :post_status_changes, only: [:index]
    end
    
    resources :boards, only: [:index, :create, :update, :destroy, :show] do
      patch 'update_order', on: :collection
    end
  
    resources :post_statuses, only: [:index, :create, :update, :destroy] do
      patch 'update_order', on: :collection
    end
  
    namespace :site_settings do
      get 'general'
      get 'boards'
      get 'post_statuses'
      get 'roadmap'
      get 'users'
      get 'authentication'
    end
  end

  # Healthcheck endpoint
  get '/health', to: proc {
    Tenant.first # to make sure db works
    [200, {}, ['success']]
  }
end

app/controllers/site_settings_controller.rb
class SiteSettingsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_admin,
    only: [:general, :boards, :post_statuses, :roadmap, :authentication]

  before_action :authenticate_moderator,
    only: [:users]
  
  def general
  end

  def boards
  end

  def post_statuses
  end

  def roadmap
  end

  def users
  end

  def authentication
  end
end

app/views/site_settings/_menu.html.erb
<div class="sidebar">
  <div class="sidebarBox">
    <span class="boxTitleText"><%= t('site_settings.menu.title') %></span>
    
    <div class="verticalNavigation" role="tablist" aria-orientation="vertical">
      <% if current_user.admin? %>
        <%= render 'menu_link', label: t('site_settings.menu.general'), path: site_settings_general_path %>
        <%= render 'menu_link', label: t('site_settings.menu.authentication'), path: site_settings_authentication_path %>
        <%= render 'menu_link', label: t('site_settings.menu.boards'), path: site_settings_boards_path %>
        <%= render 'menu_link', label: t('site_settings.menu.post_statuses'), path: site_settings_post_statuses_path %>
        <%= render 'menu_link', label: t('site_settings.menu.roadmap'), path: site_settings_roadmap_path %>
      <% end %>
      
      <%= render 'menu_link', label: t('site_settings.menu.users'), path: site_settings_users_path %>
    </div>
  </div>
</div>

app/views/site_settings/_menu_link.html.erb
<a
  href="<%= path %>"
  class="nav-link<%= current_page?(path) ? ' active' : '' %>"
  role="tabs"
  aria-controls="v-pills-home"
>
  <%= label %>
</a>

app/views/site_settings/authentication.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Authentication',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

app/views/site_settings/boards.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Boards',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

app/views/site_settings/general.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/General',
        {
          originForm: {
            siteName: @tenant.site_name,
            siteLogo: @tenant.site_logo,
            brandDisplaySetting: @tenant_setting.brand_display,
            showVoteCount: @tenant_setting.show_vote_count,
            showVoteButtonInBoard: @tenant_setting.show_vote_button_in_board,
            rootBoardId: @tenant_setting.root_board_id.to_s,
            showRoadmapInHeader: @tenant_setting.show_roadmap_in_header,
            collapseBoardsInHeader: @tenant_setting.collapse_boards_in_header,
            locale: @tenant.locale
          },
          boards: @tenant.boards.order(order: :asc),
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

app/views/site_settings/post_statuses.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/PostStatuses',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

app/views/site_settings/roadmap.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Roadmap',
        {
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>

app/views/site_settings/users.html.erb
<div class="twoColumnsContainer">
  <%= render 'menu' %>
  <div>
    <%=
      react_component(
        'SiteSettings/Users',
        {
          currentUserEmail: current_user.email,
          currentUserRole: current_user.role,
          authenticityToken: form_authenticity_token
        }
      )
    %>
  </div>
</div>